[package]
name = "roflux"
version = "0.0.2"
edition = "2021"

[[bin]]
name = "roflux"
path = "src/main.rs"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
base64 = "0.23.1"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
globset = "0.4.20"
include_dir = "0.7.4"
mlua = { version = "0.11", features = ["luau", "vendored", "send", "serialize"] }
notify = "8"
rbx_binary = "3.0.0"
rbx_dom_weak = "4.2.0"
rbx_reflection = "7.0.0"
rbx_reflection_database = "3.0.0"
rbx_types = "3.1.0"
rbx_xml = "3.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.11.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "net", "signal"] }
toml = "1.1.6"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60", features = ["Win32_System_Console", "Win32_Foundation"] }
